name: Build Posture Shield APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Quotes are mandatory here to prevent 3.10 becoming 3.1
          python-version: '3.10'

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: '3.10'
          buildozer-cmd: buildozer -v android debug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PostureShield-Android
          path: bin/*.apk